# Generated by Django 5.0.8 on 2024-08-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_orderitem_order_order_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
