# Generated by Django 5.0.8 on 2024-08-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_orderitem_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='done',
            new_name='is_done',
        ),
    ]
